services:
  application:
    build: 
      context:    .
      dockerfile: Dockerfile
      network:    "host"
    ports:
      - "127.0.0.1:80:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000"]
      interval: 1m
      timeout: 10s
      retries: 3